### PR TITLE
Providee default SDElements that all implementations of EventType share

### LINKED ISSUE #45: Implement an object that provides default SDElements that all implementations of EventType share
Every implementation of `EventType` interface must implement a `Set<SDElement> sdElements() throws PluginException` method.
Current implementations share a lot of the same code in the methods, but some types have additional SDElements that they provide.
An object, which provides the shared `SDElements` should be implemented to avoid the duplicated code.

> is this shared exactly in each type? perhaps we should have an object for this as well such as DefaultTypeSDE or so. @eemhu comments please and issue if relevant.

> there are some slight variances between some of the types, perhaps the elements that always are the same could be moved into an object.

_Originally posted by @kortemik in https://github.com/teragrep/nlf_01/pull/42#discussion_r2454078548 and replied to by @eemhu in https://github.com/teragrep/nlf_01/pull/42#discussion_r2454099735_

### PR DESCRIPTION
**Pull request by MoonBow-1**
## Description
Closes #45

A new object that provides SDElements that are shared by EventType implementations.

#### General

- [x] I have checked that my test files and functions have meaningful names.
- [x] I have checked that each test tests only a single behavior.
- [x] I have done happy tests.
- [x] I have tested only my own code.
- [x] I have tested at least all public methods.

#### Assertions

- [x] I have checked that my tests use assertions and not runtime overhead.
- [x] I have checked that my tests end in assertions.
- [x] I have checked that there is no comparison statements in assertions.
- [x] I have checked that assertions are in tests and not in helper functions.
- [x] I have checked that assertions for iterables are outside of for loops and both sides of the iteration blocks.
- [x] I have checked that assertions are not tested inside consumers.

#### Testing Data

- [x] I have tested algorithms and anything else with the possibility of unbound growth.
- [x] I have checked that all testing data is local and fully replaceable or reproducible or both.
- [x] I have checked that all test files are standalone.
- [x] I have checked that all test-specific fake objects and classes are in the test directory.
- [x] I have checked that my tests do not contain anything related to customers, infrastructure or users.
- [x] I have checked that my tests do not contain non-generic information.
- [x] I have checked that my tests do not do external requests and are not privately or publicly routable.

#### Statements

- [x] I have checked that my tests do not use throws for exceptions.
- [x] I have checked that my tests do not use try-catch statements.
- [x] I have checked that my tests do not use if-else statements.

#### Java

- [x] I have checked that my tests for Java uses JUnit library.
- [x] I have checked that my tests for Java uses JUnit utilities for parameters.

#### Other

- [x] I have only tested public behavior and not private implementation details.
- [x] I have checked that my tests are not (partially) commented out.
- [x] I have checked that hand-crafted variables in assertions are used accordingly.
- [ ] I have tested [Object Equality](https://docs.oracle.com/javase/6/docs/api/java/lang/Object.html#equals%28java.lang.Object%29).
- [x] I have checked that I do not have any manual tests or I have a valid reason for them and I have explained it in the PR description.

### Code Quality

- [x] I have checked that my code follows metrics set in Procedure: Class Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Method Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Object Quality.
- [x] I have checked that my code does not have any NULL values.
- [x] I have checked my code does not contain FIXME or TODO comments.

### CODE REVIEW

File: src/main/java/com/teragrep/nlf_01/util/DefaultSDElements.java [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+    private final String realHostname;
+    private final String className;
+
+    public DefaultSDElements(final ParsedEvent parsedEvent, final String realHostname, final String className) {
+        this.parsedEvent = parsedEvent;
+        this.realHostname = realHostname;
+        this.className = className;
+    }
+
+    public DefaultSDElements(final ParsedEvent parsedEvent, final String realHostname, final Class<?> inputClass) {
```
Comment (eemhu) [inline src/main/java/com/teragrep/nlf_01/util/DefaultSDElements.java]: preferred to have secondary ctor first, and primary ctor last.

File: src/test/java/com/teragrep/nlf_01/types/ADFActivityRunTypeTest.java [hunk 2]
```diff
@@ -258,4 +263,55 @@ void testWithMissingJsonKeys() {
...
+        systemPropertiesMap.put("PartitionKey", "456");
+        systemPropertiesMap.put("SequenceNumber", "12345678900");
+
+        final Map<String, Object> propertiesMap = new HashMap<>();
+        propertiesMap.put("prop-key", "prop-value");
+        propertiesMap.put(null, "important-null-value");
+        propertiesMap.put("important-key", null);
+
+        final ParsedEvent parsedEvent = testEvent(
+                "src/test/resources/adfactivityrun.json", new EventPartitionContextImpl(partitionContextMap), new EventPropertiesImpl(propertiesMap), new EventSystemPropertiesImpl(systemPropertiesMap), new EnqueuedTimeImpl("2010-01-01T00:00:00"), new EventOffsetImpl("0")
```
Comment (eemhu) [inline src/test/java/com/teragrep/nlf_01/types/ADFActivityRunTypeTest.java]: why not use fakes?

File: src/main/java/com/teragrep/nlf_01/util/DefaultSDElements.java (hunk 1 above)
Comment (MoonBow-1) [reply src/main/java/com/teragrep/nlf_01/util/DefaultSDElements.java]: Reordered constructors in commit d6dab44a

**Review by eemhu — APPROVED** [review]
